### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by dgreisen** [openlawlibrary/stelae#11]
## Goals
Goals
- merge server.py with publish server into single executable proxied behind nginx for production
  - run on ios/android
- migrate to TAF updater
- multi-jurisdiction
- history v2
  - integrate preview into history
  - search history
  - view future versions
  - view information about changes between versions

## Thrust 1a: Rust Publish Server
- [ ] Rust transition mvp:
  - [x] transition git.vpc to rust
  - [x] stele -> stelae https://github.com/openlawlibrary/stele/pull/14
  - [x] #13 https://github.com/openlawlibrary/stele/pull/15
  - [x] Devops
  - [x] #18
  ~[ ] #16~
  - [x] #17
  - [x] #24
  - [x] serve redirects
  - [x] #20
  - [x] remove git.vpc and corresponding routes
  - [ ] TAF: support updating bare repositories 

## Thrust 2: Implement Publish Pull in Rust
* [ ] TAF: support handlers that are arbitrary executables; pass data via stdin 
* [ ] re-implement TAF handlers in rust.

## Thrust 3a: Multi-jurisdiction per host
* [ ] enumerate security issues with multi-jurisdiction per host with plans for each issue
  * what happens if a "rogue" jurisdiction that tries to serve data for a different jurisdiction...
  * right now we support multiple hosts, one jurisdiction per host

## Thrust 3b: History v2
* [ ] ...
